import Head from "next/head";

import { Image } from 'antd/lib';
import Title from "antd/lib/typography/Title";

import dynamic from 'next/dynamic';

const DownloadBtn = dynamic(() => import("./components/DownloadBtn/DownloadBtn"), { ssr: false });

const LoadingBlock = dynamic(() => import("./components/LoadingBlock/LoadingBlock"), { ssr: false });

const UploadForm = dynamic(() => import("./components/UploadForm/UploadForm"), { ssr: false });

const MapPartData = dynamic(() => import("./components/MapPartData/MapPartData"), { ssr: false });

const ModelBlock = dynamic(() => import("./components/ModelBlock/ModelBlock"), { ssr: false });

const DrawerBlock = dynamic(() => import("./components/DrawerBlock/DrawerBlock"), { ssr: false });

const TypeErrorMessage = dynamic(() => import("./components/TypeErrorMessage/TypeErrorMessage"), { ssr: false });


export default function Home() {

  return (
    <>
      <Head>
        <title>Map generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"main-container"}>

        <Image className={"mainImg"} preview={false} src="img/svg/ak.svg"></Image>

        <Title className={"h1"}><span className={"titleBlock"}><span>Генератор</span><span>.mooe</span></span></Title>

        <main className={"main-block"}>

          <UploadForm />

          <TypeErrorMessage />

          <LoadingBlock />

          <DownloadBtn />

          <MapPartData />

          <ModelBlock />

          <DrawerBlock />

        </main>
      </div>
    </>
  );
}
