import Head from "next/head";
import { ChangeEvent, FormEvent, useCallback, useRef, useState } from "react";

import { Image } from 'antd/lib';
import Title from "antd/lib/typography/Title";

import dynamic from 'next/dynamic';

// import Worker from "worker-loader!@/workers/worker.ts";

const DownloadBtn = dynamic(() => import("./components/DownloadBtn/DownloadBtn"), { ssr: false });

const LoadingBlock = dynamic(() => import("./components/LoadingBlock/LoadingBlock"), { ssr: false });

const UploadForm = dynamic(() => import("./components/UploadForm/UploadForm"), { ssr: false });

export default function Home() {

  const [time, setTime] = useState([0, 0]);

  const [href, setHref] = useState(null);

  const [loading, setLoading] = useState<boolean>(false);

  const [isMessageShow, setIsMessageShow] = useState<boolean>(false);


  const refInputFiles = useRef(null);

  const refTime = useRef([0, 0]);

  const refFileName = useRef<string | null>(null);


  const readFile = useCallback((evt: ChangeEvent<HTMLInputElement>) => {

    if (!evt.target.files) return;

    if (evt.target.files[0].name.split(".").at(-1) !== "mooe") {
      setIsMessageShow(true);
      return
    };

    setLoading(true);

    const file = evt.target.files[0];
    const reader = new FileReader();
    reader.readAsText(file);

    refFileName.current = file.name;

    reader.onload = async () => {

      console.log(reader.result);

      setHref(null);

      setLoading(false);

    };

    reader.onerror = () => {
      console.error(reader.error);
    };

  }, [refFileName.current]);

  const restFiles = useCallback((evt: FormEvent<HTMLFormElement>) => {
    setHref(null);
    setIsMessageShow(false);
    evt.currentTarget.reset();
    refFileName.current = null;
    setTime([0, 0]);
    refTime.current = [0, 0];
  }, [refFileName.current]);

  return (
    <>
      <Head>
        <title>Map converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"main-container"}>
        <Image preview={false} style={{ width: "50vw", maxWidth: "500px" }} src="img/svg/ak.svg"></Image>
        <Title className={"h1"}><span className={"titleBlock"}><span>Генератор</span><span>.mooe</span></span></Title>
        <main className={"main-block"}>

          <UploadForm
            loading={loading}
            refFileName={refFileName}
            refInputFiles={refInputFiles}
            restFiles={restFiles}
            readFile={readFile}
          />

          {isMessageShow && <p className={"message"}>Необходим файл с расширением .mooe!</p>}

          {loading && <LoadingBlock time={time} />}

          <DownloadBtn href={href} />

          {
            href && <div>
              <Title style={{ fontSize: "30px" }} className={"h2"}>Общее время генерации</Title>
              <div className={"counter"}>
                <span style={{ color: "rgba(0, 0, 0, 0.88)" }}>{time[0]}</span>
                <span> - мин. : </span>
                <span style={{ color: "rgba(0, 0, 0, 0.88)" }}>{time[1]}</span>
                <span> - сек.</span>
              </div>
            </div>
          }

        </main>
      </div>
    </>
  );
}
